### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by bakkerjoeri** [bakkerjoeri/clean-those-kids#3]
- [x] On kid cleaned
- [x] On kid getting dirt on face
- [x] For each letter appearing on the wave message?
- [x] On wave finish
- [x] On dirt particle removed (preferably going up in tone while the score message goes up)
- [x] When time is almost up (i.e. flashing time)? Or is this a music thing
- [x] On game over

**Comment by GameJelly** [comment]
Kid cleaned, meer in lijn met de andere geluidjes:
eJxjYlCy1rHiZDFyZoCChnoGhjM8bQzSLP_rHR0YYYJNCRD6jA-EnhGJyofRgRYLfoEN6VC8y6IoxNjAqC6whh8kYlgENf4aG4RhyQQVkNWCMKLFDr8G0asEIfzPHBD6pAmEPq8Oof9DoDzEDXQDALNHL3Q.

**Comment by bakkerjoeri** [comment]
Dirt gets cleaned kunnen variaties in toon en frequentie snelheid zijn op deze:
```
eJxjYlCy1rFiYNpq_FNu_38Ghtzn1bYMDMwMLgxejP_rHR0YjIwZgKCh_owPKj0jErt4mhqEZljHbmQ8kYGxgVFdYA0_SMSwCCLDeI0NwrBkgiqV1YIwosUOvwbRqwQh_M8cEPqkCYQ-rw6h_0OgPMQNdAMAvhoxxQ..
```

**Comment by bakkerjoeri** [comment]
Kid gets dirty:

```
eJxjYlCy1rFiZDsjs9SaAQjubLxhx8Bgy_CMdSP7__r_9qz8Fo5A4YZ68RQGMH3GB0LPiETlw-g0NQjNsI7dyHgiA2MDq7rAGn6QiGERRIb1GhuEYckEVSqrBWFEix1-DaJXCUL4nzkg9EkTCH1eHUL_h0B5iBvoBgD3DTIK
```

**Comment by bakkerjoeri** [comment]
Wave clear maybe?

```
eJxjYlCy1rHiZJtpu0OOAQiOu4TbMzCc4WFm2M7xv97RgZEBDBrqmxIg9BkfCD0jEpUPo__Xi74D0UAOHy8jI2MDo7rAGn6QiGERRAXDNTYIw5IJKiCrBWFEix1-DaJXCUL4nzkg9EkTCH1eHWYHGMpD3EA3AADntDAq
```

```
eJxjYlCy1rFiZI216lBkAILjLuH2DAxneJgZtnP8r3d0YPHPBQk31BsZQ-gzPhB6RiQqH0b_rxd9B6KBHD5eRkbGBkZ1gTX8IBHDIogKhmtsEIYlE1RAVgvCiBY7_BpErxKE8D9zQOiTJhD6vDrMDjCUh7iBbgAAqwov9w..
```

**Comment by GameJelly** [comment]
More kid cleaned:
eJxjYijf3qJhyGZk3qLNAAYN9bpMd_jOMTIz_K9nYGBh99kjAhKUY73hB6I5eMw5QfQ-eYjiMz6odJoahGZYx25kPBHE_m8PEYHRRAgwoPJhZs6IhIpDoDyETzcAAAExMUM.

Sound for letter appearing:
eJxjYijf3qLByHHGhgEKGuqbGWYwMzMwM_yvZ2BgNTKGCM5KgdBnfCD0jEhUPoxOU4PQDOvYjYwngtj_7SEiMJoIAQZUPsxMmJ3_IVAewqcbAACr9TAO

Sound for "time almost up" (higher frequency for every second closer to 0):
eJxjYijf3qLByGpk3v2MAQwa6h-zxvMzMzAz_K9nYGD01IEIfquF0AwMNfIgekYkhL9FHULrqEHoNCjNsI7dyHgiiP3fHiICo4kQYEDlw8yE2fkfAuUhfLoBAPHDMBY.
